### PR TITLE
Shirley's work on spell animation

### PR DESCRIPTION
**Pull request by moates**

### CODE REVIEW

**Comment by moates** [comment]
**to fix**

@shrlyhe I'm still seeing emoji compatibility issues! i think i commented elsewhere about how emojis are different based on browser/OS/etc. not all are well-supported. 

image

**Comment by moates** [comment]
**to fix**

@shrlyhe there is an accessibility setting called "Show motion". If a player has that setting disabled, we should not show them animations. To do this, the quickest way is probably to add a flag around your sections that have animations. Code wil look something like <<if settings.showMotion>> [...div with the animation class] <<else>> [div without the animation class <</if>>

Could you give this a whirl and just lmk if you get stuck? 

image

**Comment by moates** [comment]
font choice on point !!! <3333

**Comment by moates** [comment]
**to fix**

the UI bar gets all wonky here hmmmmm. i'm guessing it has something to do with the fact that you're using _margin_ to control movement in the _move_ section. iirc there's a CSS function named something like _transform_ that can control movement and should hopefully avoid messing up the rest of the page?
 
image

**Comment by moates** [comment]
**small low-priority fix**
not sure if this is intentional, but the "What should you do now?" link appears with the other two chat options. I'd vote that you either just leave on the page the whole time (so someone can skip the chat bubbles if they want) or make it appear at the end of the chat convo



image

**Comment by moates** [comment]
overall, really cool work & a really strong start! especially impressed since you said you've never worked with CSS animations before. thank you for the help !!!!

let me know if you get stuck on any of these fixes I suggested.

**Comment by shrlyhe** [comment]
> 

does this apply to the text getting typed too? ie. `<<type 20ms start 0.5s>>`? also for the `start-spell` passage I have a transition set on the `body.screen-turns-black`....do you know how i can acccess the animation there?

**Comment by shrlyhe** [comment]
> **to fix**
> 
> @shrlyhe there is an accessibility setting called "Show motion". If a player has that setting disabled, we should not show them animations. To do this, the quickest way is probably to add a flag around your sections that have animations. Code wil look something like <> [...div with the animation class] <> [div without the animation class <>
> 
> _noReason-real-story_ passage has an example. Could you give this a whirl and just lmk if you get stuck?
> 
> image

does this apply to the text getting typed too? ie. <<type 20ms start 0.5s>>? also for the start-spell passage I have a transition set on the body.screen-turns-black....do you know how i can acccess the animation there?

**Comment by moates** [comment]
> > **to fix**
> > @shrlyhe there is an accessibility setting called "Show motion". If a player has that setting disabled, we should not show them animations. To do this, the quickest way is probably to add a flag around your sections that have animations. Code wil look something like <> [...div with the animation class] <> [div without the animation class <>
> > _noReason-real-story_ passage has an example. Could you give this a whirl and just lmk if you get stuck?
> > image
> 
> does this apply to the text getting typed too? ie. <<type 20ms start 0.5s>>? also for the start-spell passage I have a transition set on the body.screen-turns-black....do you know how i can acccess the animation there?

Yes, ideally for all text getting typed! But that's lower priority than the disorienting/spinning/movement animations.

The background color transitions are probably okay to keep, especially if they're slow and don't feel like flashing.

**Pull request merged**
